url: https://fwollatz.github.io
baseurl: 

# Site settings
title: Frederik Wollatz
email: frederik.wollatz@web.de
description: "I am a student of Cognitive Science, always motivated to search and find innovative concepts to work on!"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: linkedin.com/in/frederik-wollatz
  - title: github
    url: http://github.com/fwollatz


# Postal address (add as many lines as necessary)
address:
  - line: I DONT WANT YOU TO KNOW
  - line: I DONT WANT YOU TO KNOW

# Build settings
markdown: kramdown
permalink: pretty
